### ISSUE TITLE
이거 왜이러나요

### ISSUE THREAD

**Issue by umg1** [noonmaru/psychics#59]
[Kotlin] Enabling Kotlin v1.4.10
[18:42:04] [Server thread/INFO]: [Kotlin] Kotlin library loaded
[18:42:04] [Server thread/INFO]: [InvFX] Enabling InvFX v1.3.0
[18:42:04] [Server thread/INFO]: [Psychics] Enabling Psychics v0.7.2
[18:42:04] [Server thread/INFO]: [Psychics] Updated abilities(0):
[18:42:05] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
[18:42:05] [Server thread/WARN]:        at com.github.noonmaru.psychics.AbilityType.<clinit>(AbilityType.kt:26)
[18:42:05] [Server thread/WARN]:        at com.github.noonmaru.psychics.AbilityConcept.<init>(AbilityConcept.kt:64)
[18:42:05] [Server thread/WARN]:        at com.github.noonmaru.psychics.ability.boomerang.AbilityBoomerangConcept.<init>(Boomerang.kt:36)
[18:42:05] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:42:06] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.testCreateInstance(AbilityLoader.kt:91)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.access$testCreateInstance(AbilityLoader.kt:1)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoader.load$psychics_common(AbilityLoader.kt:48)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadAbilities$psychics_common(PsychicManager.kt:126)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:63)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:44)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:477)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:403)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:429)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:206)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:788)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:155)
[18:42:06] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:42:06] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
[18:42:06] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[18:42:06] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:42:06] [Server thread/WARN]:        ... 24 more
[18:42:06] [Server thread/WARN]: [Psychics] Failed to load Ability com.github.noonmaru.boomerang.jar
[18:42:06] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.github.noonmaru.psychics.AbilityType
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.AbilityConcept.<init>(AbilityConcept.kt:64)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.ability.flyingsword.FlyingSwordConcept.<init>(FlyingSword.kt:38)
[18:42:06] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:42:06] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.testCreateInstance(AbilityLoader.kt:91)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.access$testCreateInstance(AbilityLoader.kt:1)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoader.load$psychics_common(AbilityLoader.kt:48)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadAbilities$psychics_common(PsychicManager.kt:126)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:63)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:44)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:477)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:403)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:429)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:206)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:788)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:155)
[18:42:06] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:42:06] [Server thread/WARN]: [Psychics] Failed to load Ability com.github.noonmaru.flying-sword.jar
[18:42:06] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.github.noonmaru.psychics.AbilityType
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.AbilityConcept.<init>(AbilityConcept.kt:64)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.ability.magicarrow.MagicArrowConcept.<init>(MagicArrow.kt:34)
[18:42:06] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:42:06] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.testCreateInstance(AbilityLoader.kt:91)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.access$testCreateInstance(AbilityLoader.kt:1)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoader.load$psychics_common(AbilityLoader.kt:48)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadAbilities$psychics_common(PsychicManager.kt:126)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:63)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:44)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:477)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:403)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:429)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:206)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:788)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:155)
[18:42:06] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:42:06] [Server thread/WARN]: [Psychics] Failed to load Ability com.github.noonmaru.magic-arrow.jar
[18:42:06] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class com.github.noonmaru.psychics.AbilityType
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.AbilityConcept.<init>(AbilityConcept.kt:64)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.ability.straightshuriken.StraightShurikenConcept.<init>(StraightShuriken.kt:31)
[18:42:06] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:42:06] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.testCreateInstance(AbilityLoader.kt:91)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.access$testCreateInstance(AbilityLoader.kt:1)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoader.load$psychics_common(AbilityLoader.kt:48)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadAbilities$psychics_common(PsychicManager.kt:126)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:63)
[18:42:06] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:44)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
[18:42:06] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:477)
[18:42:06] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:403)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.loadWorld(MinecraftServer.java:429)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:206)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:788)
[18:42:06] [Server thread/WARN]:        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:155)
[18:42:06] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:42:06] [Server thread/WARN]: [Psychics] Failed to load Ability com.github.noonmaru.straight-shuriken.jar
[18:42:06] [Server thread/INFO]: [Psychics] Loaded abilities(0):
[18:42:06] [Server thread/INFO]: [Psychics] Loaded psychics(0):
[18:42:06] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:42:06] [Server thread/INFO]: Done (29.685s)! For help, type "help"

뭐죠.. 처음엔 1.16.3으로 서버 열었다가 이런문구가 떠서
1.16.1로 바꿔봤는데 저렇게 뜨네요
wiki보고 받으라는 플러그인 다 받았는데 왜이러나요
서버 내에서 명령어를 치려하면
![image](https://user-images.githubusercontent.com/72550510/95443215-48bd2880-0997-11eb-9fdf-4098f6f7adc1.png)

계속 이렇게만 뜨네요...

**Comment by ohgi07** [comment]
저 문구는 능력자 플러그인을 로딩하며 생기는 자연스러운 현상이니 안심하시고 1.16.3으로 여세요.
능력자 플러그인은 1.16.1은 지원하지 않으니 당연히 1.16.1에서는 명령어가 안 먹힙니다

**Comment by umg1** [comment]
저 근데 제가 저 글에 1.16.3으로 먼저 열었다가 안돼서 1.16.1로 한건데...제가 1.16.3으로 열었을때도 저문구가 떴었고 전 리스타트하면 될거같다생각해서 계속 한건데 안되더군요,,ㅜㅜ 그래도 일단 다시 시도는 해보겠습니다 감사합니다

**Comment by umg1** [comment]
1.16.3으로 다시 해봤는데도 이러네요
![image](https://user-images.githubusercontent.com/72550510/95460940-909c7980-09b0-11eb-8eed-a4e4c5e45f82.png)
계속 없다고 뜨고
플러그인도 다 넣었고
올라와있는 기본 능력 4개도 어빌리티 파일에 잘 넣었는데 왜이럴까요ㅜㅜ
pl치면 플러그인 다 뜨고
각별님이 올리신 영상 보면
/psychics info 뒤에 능력 목록이 뜨던데
전 안뜨고 그대로 따라 쳐봐도 안되네요

**Comment by patrick-mc** [comment]
`Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor`

해당 오류는 bungee api가 들어있지 않은 CraftBukkit 서버로 열때 생기는 오류인 것으로 알고 있습니다.
Paper 1.16.3의 가장 최신 빌드로 실행하신게 맞나요..?
