### ISSUE TITLE
플레이어에 능력추가후 리로드시 눌 에러

### ISSUE THREAD

**Issue by moJobSrc** [noonmaru/psychics#62]
[00:07:19 WARN]: java.lang.NullPointerException
[00:07:19 WARN]:        at com.github.noonmaru.psychics.tap.event.EventEntity.unregister(EventEntity.java:51)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.tap.event.RegisteredEntityListener.unregister(RegisteredEntityListener.java:65)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.Psychic.onDisable(Psychic.kt:210)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.Psychic.setEnabled(Psychic.kt:104)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.Psychic.destroy$psychics_common(Psychic.kt:437)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.Esper.removePsychic$psychics_common(Esper.kt:100)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.PsychicManager.reload$psychics_common(PsychicManager.kt:56)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.reloadPsychics(PsychicPlugin.kt:114)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:101)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.command.CommandPsychic$register$1$6$1.invoke(CommandPsychic.kt:41)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.kommand.KommandDispatcher.dispatch$kommand(KommandDispatcher.kt:110)
[00:07:19 WARN]:        at com.github.noonmaru.psychics.kommand.KommandAdapter.onCommand(KommandDispatcher.kt:250)
[00:07:19 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[00:07:19 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[00:07:19 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.dispatchCommand(CraftServer.java:802)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.handleCommand(PlayerConnection.java:1908)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:1719)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:47)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.PacketPlayInChat.a(PacketPlayInChat.java:5)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003)
[00:07:19 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[00:07:19 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by superjoy0502** [comment]
주로 해당오류는 적용하신 능력 코드에 오류가 있을 때 발생합니다. 저도 해당 상황을 많이 겪은 바로 유추해 봤습니다.

자작 능력이라면 한번 코드에 오류가 날 부분이 있는지 주석처리 하면서 디버깅 시도를 해보시는걸 추천드립니다.

혹시 아무리 봐도 에러가 일어날 것 같지 않으시다면 해당 클래스의 일부를 첨부해주시면 해결하는데 도움을 드릴 수 있을 것 같습니다.

**Comment by moJobSrc** [comment]
사용에 지장은 없어, 그냥 자잘한 버그가 있다고 이슈를 올린것입니다
코멘트 감사합니다

**Comment by superjoy0502** [comment]
아하! 사용에 지장은 없다니 다행이네요 :)
noonmaru님이 확인하셨을 때 이게 차후 프로젝트 진행에 문제가 있을 것 같을 시 버그 픽스를 해주실 듯 하네요 ㅎㅎ
항상 개발 할 때 테스트 결과, 버그 레포트는 많을수록 좋으니까요!

**Comment by noonmaru** [comment]
최신버전에서 수정했습니다.
0.9.0 버전을 사용해보세요

**Comment by moJobSrc** [comment]
확인해보았지만 0.9.0 에서도 동일한 이슈가 생깁니다.

**Comment by yoomath2018** [comment]
저도 그렇습니다

**Comment by noonmaru** [comment]
https://github.com/noonmaru/psychics/releases/tag/0.9.1

수정했습니다.

문제를 인지하고 수정한 후에 이전코드 주석처리를 하지 않았었네요
