### ISSUE TITLE
straight-shuriken을 사용할때 나는 버그

### ISSUE THREAD

**Issue by jini5012** [noonmaru/psychics#71]
오류 로그는 java.lang.AbstractMethodError: com.github.noonmaru.psychics.ActiveAbility.onCast(Lorg/bukkit/event/player/PlayerEvent;Lcom/github/noonmaru/psychics/ActiveAbility$WandAction;Ljava/lang/Object;)V
[15:18:29 WARN]:        at com.github.noonmaru.psychics.Channel.cast$psychics_common(Psychic.kt:530)
[15:18:29 WARN]:        at com.github.noonmaru.psychics.Psychic.update$psychics_common(Psychic.kt:465)
[15:18:29 WARN]:        at com.github.noonmaru.psychics.plugin.SchedulerTask.run(SchedulerTask.kt:32)
[15:18:29 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[15:18:29 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:18:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[15:18:29 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[15:18:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[15:18:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:18:29 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:18:29 WARN]:        at java.lang.Thread.run(Unknown Source)
[15:18:31 WARN]: java.lang.AbstractMethodError: com.github.noonmaru.psychics.ActiveAbility.onCast(Lorg/bukkit/event/player/PlayerEvent;Lcom/github/noonmaru/psychics/ActiveAbility$WandAction;Ljava/lang/Object;)V
[15:18:31 WARN]:        at com.github.noonmaru.psychics.Channel.cast$psychics_common(Psychic.kt:530)
[15:18:31 WARN]:        at com.github.noonmaru.psychics.Psychic.update$psychics_common(Psychic.kt:465)
[15:18:31 WARN]:        at com.github.noonmaru.psychics.plugin.SchedulerTask.run(SchedulerTask.kt:32)
[15:18:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99)
[15:18:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[15:18:31 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296)
[15:18:31 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371)
[15:18:31 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211)
[15:18:31 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999)
[15:18:31 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[15:18:31 WARN]:        at java.lang.Thread.run(Unknown Source)이거 고요.
이게 psychics에 문제가 있나요?
아님 서버 문제인가요?

**Comment by ohgi07** [comment]
psychics 버전에 맞는 버전의 능력을 사용하셨나요?
이 로그는 능력 버전이 psychics 버전과 맞지 않아 발생하는 오류입니다

**Comment by jini5012** [comment]
분명히 /psychics update를 하고 성공적이었는데 업데이트가 안된건가요?

**Comment by jini5012** [comment]
[23:07:37 INFO]: [Psychics] Enabling Psychics v0.9.2
[23:07:37 INFO]: [Psychics] Updated abilities(0):
[23:07:37 INFO]: [Psychics] Loaded abilities(4):
[23:07:37 INFO]: [Psychics]   - com.github.noonmaru.boomerang v0.0.1
[23:07:37 INFO]: [Psychics]   - com.github.noonmaru.flying-sword v0.0.1
[23:07:37 INFO]: [Psychics]   - com.github.noonmaru.magic-arrow v0.0.1
[23:07:37 INFO]: [Psychics]   - com.github.noonmaru.straight-shuriken v0.0.1
[23:07:37 INFO]: [Psychics] Loaded psychics(4):
[23:07:37 INFO]: [Psychics]   - boomerang
[23:07:37 INFO]: [Psychics]   - flying-sword
[23:07:37 INFO]: [Psychics]   - magic-arrow
[23:07:37 INFO]: [Psychics]   - straight-shuriken
0.9.2맞는데?

**Comment by dinooo5252** [comment]
그래도 안되면 다시 능력 파일들을 다운로드하세요.

**Comment by jini5012** [comment]
다시 다운로드 해보고 해봤습니다 안되네요

**Comment by yoomath2018** [comment]
마크 버전 1.16.3으로 해주세요

**Comment by jini5012** [comment]
네 그래봤어요.

**Comment by devil0414** [comment]
Psychics 폴더에 yml  형식의 파일을 추가하셨나요?

**Comment by devil0414** [comment]
안 하신것 같은데

**Comment by jini5012** [comment]
서버로그를 보면 .yml넣었어요

**Comment by eric236** [comment]
paper 버킷 서버인가요?

**Comment by jini5012** [comment]
네 paper-213.jar입니다

**Comment by realteusu** [comment]
yml 파일 첨부해주실수 있나요?

**Comment by jini5012** [comment]
네`abilities:
  straight-shuriken:
    ability: com.github.noonmaru.straight-shuriken
    common:
      display-name: 직선수리검
      type: ACTIVE
      cost: 30.0
      casting-ticks: 30
      interruptible: true
      range: 127.0
      damage:
        type: RANGED
        stats:
          ATK: 7.5
      wand:
        v: 2580
        type: TRIDENT
      supply-items: []
      description:
      - 바다의 심장을 우클릭 시 직선수리검을 발사합니다.
      - 발사된 직선수리검은 최대 ${common.range} 블록을 날아가며
      - 적 혹은 블록에 부딪힐 시 폭발을 일으켜 ${straight-shuriken.shuriken-explosion-radius} 블록
      - 내의 적에게 <damage>의 피해를 입힙니다.
    straight-shuriken:
      shuriken-init-speed: 10.0
      shuriken-acceleration: 0.04
      shuriken-ticks: 100
      shuriken-explosion-radius: 15.0
      shuriken-size: 10.0
      shuriken-knockback: 10.0
display-name: straight-shuriken
health-bonus: 5.0
health-regen-per-tick: 10.0
mana: 100.0
mana-regen-per-tick: 10.0
mana-color: BLUE
description: []
`

**Comment by jini5012** [comment]
abilities:
  straight-shuriken:
    ability: com.github.noonmaru.straight-shuriken
    common:
      display-name: 직선수리검
      type: ACTIVE
      cost: 30.0
      casting-ticks: 30
      interruptible: true
      range: 127.0
      damage:
        type: RANGED
        stats:
          ATK: 7.5
      wand:
        v: 2580
        type: TRIDENT
      supply-items: []
      description:
      - 바다의 심장을 우클릭 시 직선수리검을 발사합니다.
      - 발사된 직선수리검은 최대 ${common.range} 블록을 날아가며
      - 적 혹은 블록에 부딪힐 시 폭발을 일으켜 ${straight-shuriken.shuriken-explosion-radius} 블록
      - 내의 적에게 <damage>의 피해를 입힙니다.
    straight-shuriken:
      shuriken-init-speed: 10.0
      shuriken-acceleration: 0.04
      shuriken-ticks: 100
      shuriken-explosion-radius: 15.0
      shuriken-size: 10.0
      shuriken-knockback: 10.0
display-name: straight-shuriken
health-bonus: 5.0
health-regen-per-tick: 10.0
mana: 100.0
mana-regen-per-tick: 10.0
mana-color: BLUE
description: []

**Comment by jini5012** [comment]
`type: TRIDENT
supply-items: []`
이거는 꾸민겁니다

**Comment by realteusu** [comment]
> abilities:
> straight-shuriken:
> ability: com.github.noonmaru.straight-shuriken
> common:
> display-name: 직선수리검
> type: ACTIVE
> cost: 30.0
> casting-ticks: 30
> interruptible: true
> range: 127.0
> damage:
> type: RANGED
> stats:
> ATK: 7.5
> wand:
> v: 2580
> type: TRIDENT
> supply-items: []
> description:
> - 바다의 심장을 우클릭 시 직선수리검을 발사합니다.
> - 발사된 직선수리검은 최대 ${common.range} 블록을 날아가며
> - 적 혹은 블록에 부딪힐 시 폭발을 일으켜 ${straight-shuriken.shuriken-explosion-radius} 블록
> - 내의 적에게 의 피해를 입힙니다.
> straight-shuriken:
> shuriken-init-speed: 10.0
> shuriken-acceleration: 0.04
> shuriken-ticks: 100
> shuriken-explosion-radius: 15.0
> shuriken-size: 10.0
> shuriken-knockback: 10.0
> display-name: straight-shuriken
> health-bonus: 5.0
> health-regen-per-tick: 10.0
> mana: 100.0
> mana-regen-per-tick: 10.0
> mana-color: BLUE
> description: []

이걸 그대로 작성해서 테스트해도 아무런 문제가 없었습니다.

[abilities.zip](https://github.com/noonmaru/psychics/releases/download/0.9.2/abilities.zip) 파일을 다시 받아보셔서 다시 적용시켜보시겠어요?

**Comment by jini5012** [comment]
네 알겠습니다 되면 이슈 닫겠습니다

**Comment by jini5012** [comment]
아 다시 다운받고 하니까 되네요.감사합니다
