### ISSUE TITLE
염치없지만 한번 올려봅니다.

### ISSUE THREAD

**Issue by mashewatermelons** [noonmaru/psychics#76]
그... 플러그인 사용 단 한번도 안해봤다가 각별님이 만든 플러그인이 너무 써보고 싶어서...
한번 다운로드 한 뒤, wiki쪽에 있는 절차를 조금씩 밟고 구성하기 까지는 됬는데..
작성하기 부터 문제가 발생했습니다.
Failed to load psychic sample.yml
자.. 뭔뜻인지는 압니다. sample.yml 파일 로드가 실패했다는 건데
저는 처음부터 끝까지 모든 절차를 Wiki에 올라와있는 대로 했습니다.
그래도 되지 않자 sample.yml에 있는 boomerang(어빌리티 파일 안에 든 능력중 하나)만 빼고
잠시 옮기고 다시 해본 결과 또 sample.yml을 로드 실패했다는 말만 뜹니다.
어떻게 할 수 없나요..? 로그도 보여드리겠습니다.
*** Error, this build is outdated ***
*** Please download a new build as per instructions from https://www.spigotmc.org/go/outdated-spigot ***
*** Server will start in 20 seconds ***
Loading libraries, please wait...
[18:43:23] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[18:43:23] [main/INFO]: Reloading ResourceManager: Default, bukkit
[18:43:24] [Worker-Main-11/INFO]: Loaded 7 recipes
[18:43:23] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[18:43:23] [main/INFO]: Reloading ResourceManager: Default, bukkit
[18:43:24] [Worker-Main-11/INFO]: Loaded 7 recipes
[18:43:25] [Server thread/INFO]: Starting minecraft server version 1.16.3
[18:43:25] [Server thread/INFO]: Loading properties
[18:43:25] [Server thread/INFO]: Default game type: SURVIVAL
[18:43:25] [Server thread/INFO]: Generating keypair
[18:43:25] [Server thread/INFO]: Starting Minecraft server on *:25565
[18:43:25] [Server thread/INFO]: Using default channel type
[18:43:26] [Server thread/INFO]: This server is running CraftBukkit version git-Bukkit-890130b (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[18:43:27] [Server thread/INFO]: [Kotlin] Loading Kotlin v1.4.10
[18:43:27] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.0-SNAPSHOT-b482
[18:43:27] [Server thread/WARN]: [ProtocolLib] Version (MC: 1.16.3) has not yet been tested! Proceed with caution.
[18:43:27] [Server thread/INFO]: [InvFX] Loading InvFX v1.3.0
[18:43:27] [Server thread/INFO]: [Psychics] Loading Psychics v0.9.2
[18:43:27] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v4.6.0-SNAPSHOT-b482
[18:43:27] [Server thread/INFO]: [ProtocolLib] Started structure compiler thread.
[18:43:27] [Server thread/INFO]: Preparing level "world"
[18:43:28] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[18:43:28] [Server thread/INFO]: Preparing spawn area: 0%
[18:43:28] [Server thread/INFO]: Preparing spawn area: 0%
[18:43:30] [Worker-Main-15/INFO]: Preparing spawn area: 83%
[18:43:30] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[18:43:30] [Worker-Main-15/INFO]: Preparing spawn area: 83%
[18:43:30] [Worker-Main-13/INFO]: Preparing spawn area: 83%
[18:43:31] [Worker-Main-15/INFO]: Preparing spawn area: 95%
[18:43:31] [Worker-Main-9/INFO]: Preparing spawn area: 95%
[18:43:31] [Server thread/INFO]: Time elapsed: 3864 ms
[18:43:31] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[18:43:32] [Server thread/INFO]: Preparing spawn area: 0%
[18:43:32] [Worker-Main-10/INFO]: Preparing spawn area: 83%
[18:43:32] [Worker-Main-8/INFO]: Preparing spawn area: 83%
[18:43:33] [Worker-Main-13/INFO]: Preparing spawn area: 83%
[18:43:33] [Worker-Main-14/INFO]: Preparing spawn area: 83%
[18:43:34] [Worker-Main-10/INFO]: Preparing spawn area: 89%
[18:43:34] [Worker-Main-9/INFO]: Preparing spawn area: 96%
[18:43:35] [Server thread/INFO]: Time elapsed: 3160 ms
[18:43:35] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[18:43:35] [Server thread/INFO]: Preparing spawn area: 0%
[18:43:35] [Server thread/INFO]: Time elapsed: 443 ms
[18:43:35] [Server thread/INFO]: [Kotlin] Enabling Kotlin v1.4.10
[18:43:35] [Server thread/INFO]: [Kotlin] Kotlin library loaded
[18:43:35] [Server thread/INFO]: [InvFX] Enabling InvFX v1.3.0
[18:43:35] [Server thread/INFO]: [Psychics] Enabling Psychics v0.9.2
[18:43:35] [Server thread/INFO]: [Psychics] Updated abilities(0):
[18:43:35] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/md_5/bungee/api/ChatColor
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.AbilityType.<clinit>(AbilityType.kt:26)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.AbilityConcept.<init>(AbilityConcept.kt:64)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.ability.boomerang.AbilityBoomerangConcept.<init>(Boomerang.kt:37)
[18:43:35] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[18:43:35] [Server thread/WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[18:43:35] [Server thread/WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[18:43:35] [Server thread/WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[18:43:35] [Server thread/WARN]:        at java.lang.Class.newInstance(Unknown Source)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.testCreateInstance(AbilityLoader.kt:91)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoaderKt.access$testCreateInstance(AbilityLoader.kt:1)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.loader.AbilityLoader.load$psychics_common(AbilityLoader.kt:48)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadAbilities$psychics_common(PsychicManager.kt:140)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:71)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:43:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:480)
[18:43:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:426)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:203)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:786)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:155)
[18:43:35] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:43:35] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.api.ChatColor
[18:43:35] [Server thread/WARN]:        at java.net.URLClassLoader.findClass(Unknown Source)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96)
[18:43:35] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:43:35] [Server thread/WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[18:43:35] [Server thread/WARN]:        ... 24 more
[18:43:35] [Server thread/WARN]: [Psychics] Failed to load Ability com.github.noonmaru.boomerang.jar
[18:43:35] [Server thread/INFO]: [Psychics] Loaded abilities(0):
[18:43:35] [Server thread/WARN]: java.lang.NoSuchMethodError: org.bukkit.Bukkit.spigot()Lorg/bukkit/Server$Spigot;
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicConcept.initialize$psychics_common(PsychicConcept.kt:109)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:207)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:72)
[18:43:35] [Server thread/WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:343)
[18:43:35] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[18:43:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:480)
[18:43:35] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:406)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:426)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:203)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:786)
[18:43:35] [Server thread/WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$0(MinecraftServer.java:155)
[18:43:35] [Server thread/WARN]:        at java.lang.Thread.run(Unknown Source)
[18:43:35] [Server thread/WARN]: [Psychics] Failed to load Psychic sample.yml
[18:43:35] [Server thread/INFO]: [Psychics] Loaded psychics(0):
[18:43:35] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[18:43:35] [Server thread/INFO]: Done (7.993s)! For help, type "help"

어떻게 하는지 좀 알려주시길 바랍니다..

**Comment by qogusdn1017** [comment]
Spigot 말고 [Paper](https://papermc.io)로 구동 해주시길 바랍니다.

**Comment by mashewatermelons** [comment]
> Spigot 말고 [Paper](https://papermc.io)로 구동 해주시길 바랍니다.

헛... 페이퍼로만 가능한 거였군..요? 감사합니다...

**Comment by qogusdn1017** [comment]
혹여나 해결 되셨다면 이슈 닫아주세요.
